[package]
name = "srml-timestamp"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
parity-codec = { version = "3.1", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }
inherents = { package = "substrate-inherents", path = "../../core/inherents", default-features = false }
srml-support = { path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
consensus = { package = "srml-consensus", path = "../consensus", default-features = false }
runtime_io = { package = "sr-io", path = "../../core/sr-io", default-features = false }

[dev-dependencies]
substrate-primitives = { path = "../../core/primitives" }

[features]
default = ["std"]
std = [
	"consensus/std",
	"inherents/std",
	"parity-codec-derive/std",
	"parity-codec/std",
	"rstd/std",
	"runtime_io/std",
	"runtime_primitives/std",
	"serde/std",
	"srml-support/std",
	"system/std",
]
